// <auto-generated />
using AspNet_MVC;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspNet_MVC.Migrations
{
    [DbContext(typeof(AspMvcDbContext))]
    partial class AspMvcDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AspNet_MVC.Tables.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AuthorTable");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "George Orwell",
                            Nationality = "British"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Confucius",
                            Nationality = "Chinese"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Evie Pom",
                            Nationality = "German"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Leo Tolstoy",
                            Nationality = "Russian"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Jane Austen",
                            Nationality = "British"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Gabriel Garcia Marquez",
                            Nationality = "Colombian"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Homer",
                            Nationality = "Ancient Greek"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Mark Twain",
                            Nationality = "American"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Virginia Woolf",
                            Nationality = "British"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Haruki Murakami",
                            Nationality = "Japanese"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Name1",
                            Nationality = "N"
                        });
                });

            modelBuilder.Entity("AspNet_MVC.Tables.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.Property<int>("authorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("authorId");

                    b.ToTable("BookTable");

                    b.HasData(
                        new
                        {
                            Id = 12,
                            Author = "George Orwell",
                            Title = "1984",
                            Year = 1949,
                            authorId = 1
                        },
                        new
                        {
                            Id = 1,
                            Author = "Confucius",
                            Title = "The Analects",
                            Year = -475,
                            authorId = 2
                        },
                        new
                        {
                            Id = 2,
                            Author = "Evie Pom",
                            Title = "Evie�s Adventure",
                            Year = 2024,
                            authorId = 3
                        },
                        new
                        {
                            Id = 3,
                            Author = "Leo Tolstoy",
                            Title = "War and Peace",
                            Year = 1869,
                            authorId = 4
                        },
                        new
                        {
                            Id = 4,
                            Author = "Jane Austen",
                            Title = "Pride and Prejudice",
                            Year = 1813,
                            authorId = 5
                        },
                        new
                        {
                            Id = 5,
                            Author = "Gabriel Garcia Marquez",
                            Title = "One Hundred Years of Solitude",
                            Year = 1967,
                            authorId = 6
                        },
                        new
                        {
                            Id = 6,
                            Author = "Homer",
                            Title = "The Odyssey",
                            Year = -800,
                            authorId = 7
                        },
                        new
                        {
                            Id = 7,
                            Author = "Mark Twain",
                            Title = "The Adventures of Tom Sawyer",
                            Year = 1876,
                            authorId = 8
                        },
                        new
                        {
                            Id = 8,
                            Author = "Virginia Woolf",
                            Title = "Mrs Dalloway",
                            Year = 1925,
                            authorId = 9
                        },
                        new
                        {
                            Id = 9,
                            Author = "Haruki Murakami",
                            Title = "Norwegian Wood",
                            Year = 1987,
                            authorId = 10
                        },
                        new
                        {
                            Id = 11,
                            Author = "Confucius",
                            Title = "NUL",
                            Year = 0,
                            authorId = 2
                        });
                });

            modelBuilder.Entity("AspNet_MVC.Tables.Book", b =>
                {
                    b.HasOne("AspNet_MVC.Tables.Author", "author")
                        .WithMany("Books")
                        .HasForeignKey("authorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("author");
                });

            modelBuilder.Entity("AspNet_MVC.Tables.Author", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
